// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-BQnM2TkwgW9xz_dmuYGo6pne055UcYc',
    appId: '1:697807862169:android:99cbbffceafe5ac7de7b08',
    messagingSenderId: '697807862169',
    projectId: 'interview-98091',
    storageBucket: 'interview-98091.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6bVGuHg9S6J7cOpxCVjWoos_yMxxV9-4',
    appId: '1:697807862169:ios:90926b5b943586c2de7b08',
    messagingSenderId: '697807862169',
    projectId: 'interview-98091',
    storageBucket: 'interview-98091.firebasestorage.app',
    iosBundleId: 'com.example.frappeLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6bVGuHg9S6J7cOpxCVjWoos_yMxxV9-4',
    appId: '1:697807862169:ios:90926b5b943586c2de7b08',
    messagingSenderId: '697807862169',
    projectId: 'interview-98091',
    storageBucket: 'interview-98091.firebasestorage.app',
    iosBundleId: 'com.example.frappeLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVdJuLpZn81YYBW8FyVehEtZfzAoVI7Ic',
    appId: '1:697807862169:web:63faec24183a96c2de7b08',
    messagingSenderId: '697807862169',
    projectId: 'interview-98091',
    authDomain: 'interview-98091.firebaseapp.com',
    storageBucket: 'interview-98091.firebasestorage.app',
    measurementId: 'G-LCXMX1NPS9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVdJuLpZn81YYBW8FyVehEtZfzAoVI7Ic',
    appId: '1:697807862169:web:63faec24183a96c2de7b08',
    messagingSenderId: '697807862169',
    projectId: 'interview-98091',
    authDomain: 'interview-98091.firebaseapp.com',
    storageBucket: 'interview-98091.firebasestorage.app',
    measurementId: 'G-LCXMX1NPS9',
  );

}